DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
  PHONE INT(11) NOT NULL,
  NAME VARCHAR(45) NOT NULL ,
  LASTNAME VARCHAR(45) NOT NULL ,
  UNIQUE KEY uni_user_username (PHONE),
  PRIMARY KEY (PHONE)
);

DROP TABLE IF EXISTS CONTACT;
CREATE TABLE CONTACT (
  PHONE INT(11) NOT NULL,
  NAME VARCHAR(45) NOT NULL,
  UNIQUE KEY uni_role_role (PHONE),
  PRIMARY KEY (PHONE)
);

/** JOIN TABLES */

DROP TABLE IF EXISTS USERS_CONTACT;
CREATE TABLE USERS_CONTACT(
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  contact_id INT(11) NOT NULL,
  PRIMARY KEY (id)
);